sources:
  - name: budget
    database: budget_db
    schema: sources
    tables:
      - name: checking
      - name: sapphire_reserve
      - name: transaction_categories

models:
  - name: stg_checking
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
  - name: stg_sapphire_reserve
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
  - name: stg_budget_categories
    columns:
      - name: category_id
        tests:
          - not_null
          - unique
      - name: category_name
        tests:
          - not_null
          - unique
  - name: stg_transaction_categories
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
          # update once we have this model created
          # - relationships:
          #     arguments:
          #       to: ref('itm_budget_transactions')
          #       field: transaction_id
      - name: category_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_budget_categories')
                field: category_id